name: GitHub Actions Test Exercise1
run-name: ${{ github.actor }} is testing exercise1 🚀
on: [ push ]
env:
  NODE_OPTIONS: --openssl-legacy-provider
jobs:
  Test-Exercise1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 15.x, 16.x, 18.x ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages and run test
        run: |
          cd ./exercise1
          pwd
          ls
          npm i
          npm run test:smoke
