name: GitHub Actions Test Exercise1
run-name: ${{ github.actor }} is testing exercise1 🚀
on: [ push ]
jobs:
  Test-Exercise1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pwd
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: pwd
      - run: |
          cd exercise1
      - run: npm ci
      - run: npm run test:smoke
